org: mikezm
app: h2hapi
# serverless.yml

service: halfway-to-history-api

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage,'dev'}
  region: us-east-2
  # Environment variables


custom:
  wsgi:
    app: application.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  dynamodb:
    stages:
      - dev
    start:
      migrate: false
      sharedDb: true
      noStart: true # because dynamodb is already running as local service



functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'