# serverless.yml

service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local

custom:
  wsgi:
    app: application.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  dynamodb:
    stages:
      - dev
    start:
      migrate: false
      sharedDb: true
      #noStart: true # because dynamodb is already running as local service

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-2

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'